### ISSUE TITLE
when i test on MAC , suffer this problem, so what can i do for it? please

### ISSUE THREAD

**Issue by Rossichan** [huihut/Facemoji#8]
ArgumentException: The output Mat object has to be of the same size
OpenCVForUnity.Utils.webCamTextureToMat (UnityEngine.WebCamTexture webCamTexture, OpenCVForUnity.Mat mat, UnityEngine.Color32[] bufferColors) (at Assets/Plugins/OpenCVForUnity/org/opencv/unity/Utils.cs:665)

**Comment by huihut** [comment]
1. The project only supports Android(and can't run in the `UNITY_EDITOR`), are you running in Android?
2. If you are running in Android, It may be caused by setting a larger number than the camera(width or height).

    ![image](https://user-images.githubusercontent.com/23519480/54292508-4b07a700-45e9-11e9-9d7f-cb24408dfdcf.png)

3. If you are running in Android, you can debug this code.  it may be caused by the failure to new a Mat.
 `Facemoji\Assets\Plugins\DlibFaceLandmarkDetector\DlibFaceLandmarkDetectorWithOpenCVSample\WebCamTextureToMatHelper.cs`
```cs
private IEnumerator init ()
{
......
rgbaMat = new Mat (webCamTexture.height, webCamTexture.width, CvType.CV_8UC4);
......
}
```

**Comment by Rossichan** [comment]
thanks，i got it!

**Comment by huihut** [comment]
ok, I closed the issue.
